name: log-writer ci

on:
  push:
    paths:
      - 'log-writer/**'
  pull_request:
    paths:
      - 'log-writer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Add gradle wrapper
        run: gradle wrapper
      - name: Build with Gradle
        run: ./gradlew build


